from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
app=(root.parent/'Daylight.html').read_text()
# App is unchanged: srcdoc gives it a real narrow viewport, including media queries.
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daylight · mobile edition</title><style>
*{box-sizing:border-box}body{margin:0;font:14px system-ui,sans-serif;background:radial-gradient(ellipse at 20% 80%,#e2e8d8,transparent 60%),radial-gradient(ellipse at 95% 10%,#ebe1f5,transparent 70%),#f3f2ec;color:#303b2e;min-height:100dvh}header{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:18px 28px}.brand{display:flex;align-items:center;gap:7px;font-size:22px;font-weight:750;letter-spacing:-1px}.brand svg{width:24px;height:24px}.edition{font-size:10px;letter-spacing:2px;font-weight:450;margin-left:13px;color:#636f59}.switch{display:flex;border:1px solid #dce1d2;background:#fff8;padding:4px;border-radius:30px;gap:3px}button{font:inherit;font-size:12px;cursor:pointer;border:0;background:none;color:#536348;padding:9px 18px;border-radius:25px}button[aria-pressed=true]{background:#33442e;color:#f8f9f1;box-shadow:0 3px 7px #33442e19}button:focus-visible{outline:2px solid #8972a7;outline-offset:3px}.stage{margin:0 auto;width:406px;max-width:calc(100% - 30px);height:calc(100dvh - 113px);max-height:900px;min-height:530px;border:8px solid #fcfcf8;border-radius:36px;box-shadow:0 25px 65px #3e4c3820,0 0 0 1px #fff8;overflow:hidden;transition:width .35s}.stage.desktop{width:1240px;border-radius:18px}iframe{border:0;width:100%;height:100%;display:block;background:#f8f7f2}.note{text-align:center;font-size:11px;color:#65735a;margin:15px 20px 12px;line-height:1.5}.note b{font-weight:500}@media(max-width:850px){.desktop-choice{display:none}}@media(max-width:520px){header{padding:12px 17px}.brand{font-size:20px}.edition{font-size:8px;margin-left:5px;letter-spacing:1px}.switch{display:none}.stage{width:100%;max-width:none;height:calc(100dvh - 52px);max-height:none;min-height:0;border:0;border-radius:0;box-shadow:none}.note{display:none}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style></head><body><header><div class="brand"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/></svg>daylight.<span class="edition">THE MOBILE EDITION</span></div><div class="switch" aria-label="Preview size"><button aria-pressed="true" id="mobile">Mobile</button><button class="desktop-choice" aria-pressed="false" id="desktop">Desktop</button></div></header><div class="stage" id="stage"><iframe id="app" title="Interactive Daylight web app"></iframe></div><p class="note"><b>A real, interactive preview.</b> Complete the one-time setup, then try checking off a task. In-chat storage may be temporary.</p><script>
const app=document.getElementById('app');app.srcdoc=APP_CONTENT;
for(const mode of ['mobile','desktop'])document.getElementById(mode).onclick=()=>{document.getElementById('stage').classList.toggle('desktop',mode==='desktop');for(const name of ['mobile','desktop'])document.getElementById(name).setAttribute('aria-pressed',String(mode===name))};
</script></body></html>'''.replace('APP_CONTENT',json.dumps(app).replace('</','<\\/'))
p=root.parent/'Daylight-Mobile-Preview.html';p.write_text(html);print('Mobile preview ready:',p)
