import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch();const context=await browser.newContext();const page=await context.newPage();const errors=[];const failures=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push([r.url(),r.status()]);});
await page.goto('http://localhost:4174/daylight/');
await page.getByLabel('What should we call you?').fill('Sepehr');
for(let i=0;i<3;i++)await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.locator('[data-theme-option=midnight]').click();await page.getByRole('button',{name:'Let the good days begin'}).click();await expect(page.locator('.app')).toHaveAttribute('data-theme','midnight');
await expect(page.getByRole('heading',{name:'Hello, Sepehr'})).toBeVisible();
await page.evaluate(()=>document.fonts.ready);
const images=await page.locator('img').evaluateAll(imgs=>imgs.map(i=>({src:i.src,loaded:i.complete&&i.naturalWidth>0})));
if(images.some(i=>!i.loaded||!i.src.includes('/daylight/')))throw new Error('Image path/loading failure: '+JSON.stringify(images));
await page.evaluate(()=>navigator.serviceWorker.ready);
await page.reload();await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
const scope=await page.evaluate(async()=>(await navigator.serviceWorker.ready).scope);
if(!scope.endsWith('/daylight/'))throw new Error('Incorrect SW scope: '+scope);
await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Hello, Sepehr'})).toBeVisible();
await page.locator('.sidebar').getByRole('button',{name:'Focus',exact:true}).click();
await expect(page.locator('.big-clock')).toHaveText('25:00');
if(!await page.evaluate(async()=>(await fetch('/daylight/images/forest.jpg')).ok))throw new Error('Offline background missing');
await page.setViewportSize({width:390,height:844});
await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'Home',exact:true}).click();
await expect(page.getByRole('heading',{name:'Hi, Sepehr'})).toBeVisible();
for(const name of ['focus-sculpture','mindful-morning','slow-moments'])if(!await page.evaluate(async n=>(await fetch('/daylight/images/'+n+'.jpg')).ok,name))throw new Error('Mobile illustration missing offline: '+name);
await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'You',exact:true}).click();await page.getByRole('button',{name:'Good',exact:true}).click();await expect(page.getByRole('button',{name:'Good',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Save check-in',exact:true}).click();await expect(page.locator('.mood-saved')).toContainText('good');
if(errors.length||failures.length)throw new Error(JSON.stringify({errors,failures}));
console.log('PASS: /daylight/ onboarding, local images/fonts, saved profile, scoped service worker, offline reload, focus room, separate mobile UI and all three original illustrations.');
await browser.close();
