import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');
await page.setContent('<iframe id="app" sandbox="allow-scripts" style="position:fixed;inset:0;width:100%;height:100%;border:0"></iframe>');
await page.evaluate(html=>document.querySelector('iframe').srcdoc=html,fs.readFileSync('/home/user/Daylight.html','utf8'));
const frame=page.frameLocator('#app');
await expect(frame.getByRole('heading',{name:'Good days start here.'})).toBeVisible();
await frame.getByLabel('What should we call you?').fill('Alex');
for(let i=0;i<3;i++)await frame.getByRole('button',{name:'Continue',exact:true}).click();
await frame.getByRole('button',{name:'Let the good days begin'}).click();
await expect(frame.getByRole('heading',{name:'Hello, Alex'})).toBeVisible();
await expect(frame.getByText('Temporary preview session')).toBeVisible();
await frame.getByRole('button',{name:'Add task N',exact:true}).click();
await frame.getByLabel('Task title').fill('My web app works');
await frame.getByRole('dialog').getByRole('button',{name:'Add task',exact:true}).click();
await expect(frame.getByText('My web app works',{exact:true})).toBeVisible();
await page.screenshot({path:'qa/inline-preview.png',fullPage:true});
console.log('Sandboxed, no-network inline preview: onboarding, dashboard, task creation PASS');console.log('Runtime errors:',errors);
if(errors.length)process.exitCode=1;
await browser.close();
